--9 OCT 2023
SELECT * FROM JOB_HISTORY;
DESC EMPLOYEES;
SELECT (FIRST_NAME||' '||LAST_NAME) 
AS DETAILS 
FROM EMPLOYEES;

SELECT EMPLOYEE_ID,(FIRST_NAME||' '||LAST_NAME||' Having salary '||SALARY) 
AS DETAILS 
FROM EMPLOYEES;


SELECT ('EMPLOYEE'||' '||EMPLOYEE_ID||' '||'Reporting to'||' '||MANAGER_ID)
AS DETAILS 
FROM EMPLOYEES;

SELECT (FIRST_NAME||' '||LAST_NAME||' '||'Working in department'||' '||DEPARTMENT_ID)
AS DETAILS 
FROM EMPLOYEES;

SELECT  EMPLOYEE_ID,(FIRST_NAME||' '||LAST_NAME||' '||' Having salary'||' '||SALARY)
AS DETAILS 
FROM EMPLOYEES;

SELECT (FIRST_NAME||' '||LAST_NAME||' Working as '||JOB_ID||' '||'in department '||DEPARTMENT_ID) 
AS DETAILS 
FROM EMPLOYEES;

SELECT (FIRST_NAME||' '||LAST_NAME)
AS FULL_NAME ,(' Having commission '||' '||COMMISSION_PCT)
AS DETAILS 
FROM EMPLOYEES;

SELECT FIRST_NAME,('Joined company on'||' '||HIRE_DATE)
AS DETAILS 
FROM EMPLOYEES;

SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,(SALARY+0.20*SALARY)
AS NEW_SALARY 
FROM EMPLOYEES;

SELECT (FIRST_NAME||' '||LAST_NAME)
AS FULL_NAME ,DEPARTMENT_ID,HIRE_DATE 
FROM EMPLOYEES;

--WQAD those employee whose commission pct >=0.4
SELECT *
FROM EMPLOYEES 
WHERE COMMISSION_PCT >=0.4;

--WQAD those employee first name last name whose salary more than 9000 and 
--job id IT_prog . 
SELECT FIRST_NAME,LAST_NAME 
FROM EMPLOYEES 
WHERE SALARY >= 9000 AND JOB_ID='IT_PROG';

--WQAD those employee first name last name whose salary more than 9000 and job id IT_prog .
SELECT * 
FROM EMPLOYEES 
WHERE SALARY >= 9000 AND JOB_ID='IT_PROG';

--WAQD those employees whose last name king
SELECT * 
FROM EMPLOYEES 
WHERE LAST_NAME='King';

--WAQD those employee whose job_id ST clerk and manager_id 120.
SELECT * 
FROM EMPLOYEES 
WHERE JOB_ID = 'ST_CLERK' AND MANAGER_ID = 120;

--WAQD THOSE EMPLOYEES WHOSE COMMISSION PCT 0.3 OR O.2.
SELECT * FROM EMPLOYEES 
WHERE COMMISSION_PCT =0.3 OR COMMISSION_PCT = 0.2;

--WAQD those employees whose email phall and phone number 011.44.1344.
SELECT * 
FROM EMPLOYEES 
WHERE EMAIL='PHALL' AND PHONE_NUMBER ='011.44.1344.478968';

--WAQD those employee whose job_id sa_rep and salary>7000;
SELECT * 
FROM EMPLOYEES 
WHERE JOB_ID = 'SA_REP' AND SALARY > 7000;

--WAQD those employee whose manager id 100 or 145.
SELECT * 
FROM EMPLOYEES 
WHERE MANAGER_ID=100 OR MANAGER_ID=145;

--WAQD those employee whose department id 80 or 50.
SELECT * 
FROM EMPLOYEES 
WHERE DEPARTMENT_ID=80 OR DEPARTMENT_ID=50;

--WAQD those employee whose department name IT and location id 1400.
SELECT *
FROM DEPARTMENTS 
WHERE DEPARTMENT_NAME='IT' AND LOCATION_ID=1400;

--WAQD those employee whose manager id >200 or =1800
SELECT * 
FROM DEPARTMENTS 
WHERE MANAGER_ID >200 OR MANAGER_ID = 1800;

--WAQD those employees whose department id 100 and department name finance.
SELECT *
FROM DEPARTMENTS 
WHERE DEPARTMENT_ID = 100 AND DEPARTMENT_NAME = 'Finance';

--WAQD those employees whose department id  160 and LOCATION id 1700.
SELECT *
FROM DEPARTMENTS 
WHERE DEPARTMENT_ID=160 AND LOCATION_ID=1700;

--WAQD those employees whose department name benefits or manufacturing.
SELECT *
FROM DEPARTMENTS 
WHERE DEPARTMENT_NAME='Benefits' OR DEPARTMENT_NAME='Manufacturing';

--WAQD those employes working in finance or clerk.
SELECT * 
FROM DEPARTMENTS 
WHERE DEPARTMENT_NAME ='Finance' OR DEPARTMENT_NAME ='Clerk';

--WAQD those employees city venice or toronto.
SELECT * 
FROM LOCATIONS 
WHERE CITY='Venice' or CITY='Toronto';

--WAQD of employees Location_id,street address whose postal_code 00989 and city roma 
SELECT LOCATION_ID,STREET_ADDRESS 
FROM LOCATIONS 
WHERE POSTAL_CODE=00989 AND CITY='Roma';

--WAQD those employees whose country id  us or ca
SELECT * 
FROM LOCATIONS 
WHERE COUNTRY_ID='US' OR COUNTRY_ID='CA';

--WAQD those employees whose contry id ch and state_province BE.
SELECT * 
FROM LOCATIONS 
WHERE COUNTRY_ID='CH' AND STATE_PROVINCE='BE';

--WAQD those employee departmrnt id (30,20,50).
SELECT *
FROM EMPLOYEES 
WHERE DEPARTMENT_ID IN (30,20,50);

--WAQD full name of employee whose commission pct null;
SELECT (FIRST_NAME||' '||LAST_NAME)
AS FULL_NAME,COMMISSION_PCT 
FROM EMPLOYEES 
WHERE COMMISSION_PCT IS NULL;

--WAQD those employee fullname salary commission pct hire date>03-jan-06;
SELECT (FIRST_NAME||' '||LAST_NAME)
AS FULL_NAME,EMPLOYEE_ID,HIRE_DATE 
FROM EMPLOYEES 
WHERE (EMPLOYEE_ID <=100 AND HIRE_DATE <= '03-JAN-06');

--WAQD employee id,salary,hire_date of those employee whose working in it_prog ,
--clerk,AD_VP,AD_PRES AND HIRE DATE >6 -JAN-08 
SELECT EMPLOYEE_ID,SALARY,HIRE_DATE 
FROM EMPLOYEES 
WHERE JOB_ID NOT IN ('IT_PROG,CLERK,AD_VP,AD_PRES')AND SALARY >5000;

--WAQD FIRST_NAME,COMMISSION OF EMPLOYEE WHOSE COMMISSION_PCT BETWEEN 0.3 AND 0.6
SELECT FIRST_NAME,COMMISSION_PCT 
FROM EMPLOYEES 
WHERE COMMISSION_PCT BETWEEN 0.3 AND 0.6; 

--WAQD employe_id first name of those employee whose EMPLOYEE_ID 100,101,102
SELECT EMPLOYEE_ID,FIRST_NAME,JOB_ID 
FROM EMPLOYEES 
WHERE EMPLOYEE_ID IN (100,101,102);

--WAQD employee full name with 25% hike in salary of those emplose whose 
--department_id 90,100,50
SELECT (FIRST_NAME ||' '||LAST_NAME) 
AS FULL_NAME ,SALARY,(SALARY+SALARY*0.2) 
AS NEW_SALARY,DEPARTMENT_ID 
FROM EMPLOYEES 
WHERE DEPARTMENT_ID IN (90,100,50);

--WAQD OF FIRST NAME AND COMMISSION PCT those employee whose commission pct NULL
SELECT FIRST_NAME,COMMISSION_PCT 
FROM EMPLOYEES 
WHERE COMMISSION_PCT IS NULL;

--WAQD OF EMPLOYEE FIRST NAME those employee  join date 03-jan-06
SELECT FIRST_NAME FROM EMPLOYEES 
WHERE HIRE_DATE = '03-JAN-06';

--WAQD DISPLAY EMAIL OF EMPLOSE WHOSE EMPLOYEE ID 100,102,107)
SELECT EMAIL,EMPLOYEE_ID 
FROM EMPLOYEES 
WHERE EMPLOYEE_ID IN (100,102,107);

--WAQD department id of those employee whose deparment name not in 
--Administration Marketing Purchasing Human Resources Shipping
SELECT DEPARTMENT_ID,DEPARTMENT_NAME 
FROM DEPARTMENTS 
WHERE DEPARTMENT_ID IN(100,200,110);

--WAQD show those deparment name whose LOCATION_ID NOT IN (1700 1800 1700 2400 1500 1400)
SELECT DEPARTMENT_NAME 
FROM DEPARTMENTS 
WHERE LOCATION_ID NOT IN (1700,1800,1700,2400,1500,1400);

--WAQD show department name,MANAGER_ID whose manager id null;
SELECT DEPARTMENT_NAME,MANAGER_ID 
FROM DEPARTMENTS 
WHERE MANAGER_ID IS NULL;

--WAQD show department id whos manager id NOT null;
SELECT DEPARTMENT_NAME,MANAGER_ID 
FROM DEPARTMENTS 
WHERE MANAGER_ID IS NOT NULL;

--WAQD show those deparment name whose loaction id inbetween 1700 2400
SELECT DEPARTMENT_NAME 
FROM DEPARTMENTS 
WHERE LOCATION_ID BETWEEN 1700 AND 2400;

--WAQD display the loaction id where those are in between contry us and jp
SELECT LOCATION_ID 
FROM LOCATIONS 
WHERE COUNTRY_ID IN ('US','JP');

--WAQD display those city where state province null
SELECT CITY 
FROM LOCATIONS WHERE STATE_PROVINCE IS NULL;

--WAQD display those city whose postal code 1689 00989 10934
SELECT CITY 
FROM LOCATIONS 
WHERE LOCATION_ID IN (1100,1000,1200);

--WAQD display those country id whose location id in between 2000 to 2400
SELECT COUNTRY_ID 
FROM LOCATIONS 
WHERE LOCATION_ID  BETWEEN 2000 AND 2400;

--WAQD display those city whose state province not null
SELECT CITY 
FROM LOCATIONS 
WHERE STATE_PROVINCE IS NOT NULL;

--LIKE ' %'
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE 'A%';
--2]LIKE '% '
SELECT * FROM EMPLOYEESWHERE LAST_NAME LIKE '%s';
--3]KIKE '% %'
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '%b%';
--4]LIKE 'CHAR'
SELECT *FROM EMPLOYEES WHERE LAST_NAME LIKE 'Abel';
--5]LIKE '_'
SELECT * FROM LOCATIONS WHERE COUNTRY_ID LIKE 'U_';
--6]LIKE '_'
SELECT *FROM LOCATIONS WHERE CITY LIKE 'L_nd__';
--7]LIKE '% %'
SELECT *FROM LOCATIONS WHERE CITY LIKE '%e%';
--8]LIKE
SELECT * FROM LOCATIONS WHERE CITY LIKE 'V%e';
--9]LIKE
SELECT *FROM LOCATIONS WHERE CITY LIKE '%ni%';
--10]LIKE
SELECT * FROM LOCATIONS WHERE CITY LIKE 'V___%';
--11]LIKE
SELECT * FROM LOCATIONS WHERE CITY LIKE '_e%';
--12]ORDER BY
SELECT * FROM LOCATIONS ORDER BY CITY;
--13]ORDER BY
SELECT * FROM LOCATIONS ORDER BY CITY ASC;
--14]ORDER BY
SELECT * FROM LOCATIONS ORDER BY CITY DESC;

--15]WAQD display employee id ,commission pct of those employee whose commission_pct not equal to 0.3
SELECT EMPLOYEE_ID,COMMISSION_PCT 
FROM EMPLOYEES 
WHERE COMMISSION_PCT <> 0.3;

--16]All ralation operator
SELECT *
FROM LOCATIONS 
WHERE LOCATION_ID=
ALL (SELECT LOCATION_ID FROM LOCATIONS WHERE CITY ='London');

--17]ANY relational operator
SELECT * 
FROM LOCATIONS 
WHERE LOCATION_ID=
ANY (SELECT LOCATION_ID FROM LOCATIONS WHERE CITY ='London');

--18]SOME relational operator
SELECT * 
FROM LOCATIONS 
WHERE LOCATION_ID > 
SOME (SELECT LOCATION_ID FROM LOCATIONS WHERE CITY ='London');

--19]EXISTS relational operator 
SELECT *
FROM LOCATIONS 
WHERE EXISTS(SELECT LOCATION_ID FROM LOCATIONS WHERE CITY ='London');

--20]ORDER BY CLAUSE
SELECT * 
FROM EMPLOYEES 
ORDER BY SALARY DESC

--In build function(single row->case manipulation,character manipulation)
--1]WAQD disply india in lowercase 
SELECT * FROM DUAL;
SELECT LOWER('India')FROM DUAL;

--2]WAQD employee first name  in uppercase 
SELECT EMPLOYEE_ID,UPPER(FIRST_NAME) FROM EMPLOYEES;

--3]WAQD employee first name and last name in uppercase
SELECT INITCAP(FIRST_NAME)
AS FIRST_NAME,
UPPER(LAST_NAME)
AS LAST_NAME FROM EMPLOYEES;

--4]WAQD CONCAT first name and last name
SELECT CONCAT(CONCAT(FIRST_NAME,' '),LAST_NAME)
AS FULL_NAME 
FROM EMPLOYEES;

--5]WAQD SUBSTR substring
SELECT LENGTH(SUBSTR('INDIA',1,2))
FROM DUAL;

--6]WAQD SUBSTR
SELECT SUBSTR(DEPARTMENT_NAME,1,7) AS DEPARTMENT_NAME
FROM DEPARTMENTS;

--7]WAQD SUBSTR
SELECT SUBSTR(DEPARTMENT_NAME,7,7) AS DEPARTMENT_NAME
FROM DEPARTMENTS;

--8]WAQD LENGTH find length of salary department name
SELECT length(DEPARTMENT_NAME) AS DEPARTMENT_NAME
FROM DEPARTMENTS;

--9]WAQD SUBSTR WITH LENGTH
SELECT DEPARTMENT_NAME,LENGTH(SUBSTR(DEPARTMENT_NAME,1,7))AS DEPARTMENT_LENGTH
FROM DEPARTMENTS;

--10]WAQD INSTR ON CITY
SELECT INSTR(CITY,'o')AS CITY
FROM LOCATIONS
WHERE CITY='Roma';

--11]WAQD LPAD(SALARY,5,'*')
SELECT LPAD(SALARY,7,'*')
FROM EMPLOYEES;

--12]WAQD RPAD(SALARY,5,#)
SELECT RPAD(EMPLOYEE_ID,6,'*')
FROM EMPLOYEES;

--13]WAQD RPAD(SALARY,5,#)
SELECT RPAD(EMPLOYEE_ID,2,'*')
FROM EMPLOYEES;

--14]WAQD RPAD(SALARY,5,#)
SELECT RPAD(JOB_ID,16,'*')
FROM EMPLOYEES;

--15]WAQD REPLACE 
SELECT REPLACE('fan','f','t')AS NAME
FROM DUAL;

--16]TRIM 
SELECT TRIM('H' FROM 'HELLOWORLD')
FROM DUAL;

--17]SUBSTR 
SELECT FIRST_NAME,LAST_NAME
FROM EMPLOYEES 
WHERE SUBSTR(LAST_NAME,1,1)='A';

--18]INITCAP
SELECT CITY,country_id
FROM LOCATIONS
WHERE LOWER(INITCAP(COUNTRY_ID))='us';

--19]CONCAT
SELECT CONCAT(CONCAT(CITY,' '),COUNTRY_ID)
FROM LOCATIONS;

--20]TRIM
SELECT TRIM('D' FROM 'WORLD')
FROM DUAL;

--SELECT ADD_MONTH(SYSDATE,)FROM DUAL;
SELECT ADD_MONTHS(SYSDATE,INSTR('hello','e'))
AS DETAILS FROM DUAL;
--*****************************************************
--1]MONTHS_BETWEEN
SELECT HIRE_DATE, TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12) AS EXPERIENCE
FROM EMPLOYEES;

SELECT SUBSTR('INDIA',8,3)FROM DUAL;

--2] MONTHS_BETWEEN****************
SELECT HIRE_DATE,MONTHS_BETWEEN(SYSDATE,HIRE_DATE) AS MON
FROM EMPLOYEES;

--3]TRUNC NUMBER
SELECT 
TRUNC(4356.3516,-2)
FROM DUAL;

--4]TRUNC NUMBER
SELECT 
TRUNC(4356.3516,2)
FROM DUAL;

--4]TRUNC NUMBER
SELECT 
TRUNC(4356,2)
FROM DUAL;

--5]ROUND NUMBER
SELECT 
ROUND(5678.786,3)
FROM DUAL;

--6]ROUND NUMBER
SELECT 
ROUND(5678.786,-3)
FROM DUAL;

--6]ROUND NUMBER
SELECT 
ROUND(5678,3)
FROM DUAL;

--7]ROUND NUMBER
SELECT 
ROUND(-5678,3)
FROM DUAL;

--7]ROUND NUMBER
SELECT 
ROUND(-5678.675,3)
FROM DUAL;

SELECT TRUNC(1376.34,-2)FROM DUAL;
SELECT ROUND(13456.34,-1)FROM DUAL;

--8]MOD NUMBER
SELECT 
MOD(12346,5) 
FROM DUAL;

--9]MOD NUMBER
SELECT 
MOD(12346.7565,5) 
FROM DUAL;

--10]MOD NUMBER
SELECT 
MOD(45637,-5) 
FROM DUAL;

--11]ADD_MONTHS
SELECT ADD_MONTHS(SYSDATE,4)AS ADD_MON FROM DUAL;

--12]ADD_MONTHS
SELECT NEXT_DAY(HIRE_DATE,'FRIDAY')AS NEXT_DAY FROM EMPLOYEES;

--13]Last day
SELECT LAST_DAY(HIRE_DATE)AS NEXT_DAY FROM EMPLOYEES;

--14]ROUND DATE(MONTH)
SELECT ROUND(SYSDATE,'MONTH')AS RDATE FROM DUAL;

--15]ROUND DATE (MONTH)
SELECT ROUND(HIRE_DATE,'MONTH')AS RDATE FROM EMPLOYEES;

--16]ROUND DATE (YEAR)
SELECT ROUND(SYSDATE,'YEAR')AS RDATE FROM DUAL;

--17] TRUNC DATE(MONTH)
SELECT TRUNC(SYSDATE,'MONTH')AS RDATE FROM DUAL;

--18] TRUNC DATE(MONTH)
SELECT TRUNC(HIRE_DATE,'MONTH')AS RDATE FROM EMPLOYEES;

--19] TRUNC DATE(YEAR)
SELECT TRUNC(SYSDATE,'YEAR')AS RDATE FROM DUAL;

--20] TRUNC DATE(YEAR)
SELECT TRUNC(HIRE_DATE,'YEAR')AS RDATE FROM EMPLOYEES;
--******************************************************************
--1] DATE ROUND FUNCTION
SELECT ROUND(MONTHS_BETWEEN(SYSDATE,ADD_MONTHS('25-Dec-2021',-3))/12,0)
FROM DUAL;

--2] ADD_MONTHS FUNCTION
SELECT ADD_MONTHS('25-Dec2021',-3)FROM DUAL; 

--3]MONTHS_BETWEEN FUNCTION
SELECT HIRE_DATE,MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12
AS MONTHS_N
FROM EMPLOYEES;

--4]ROUND NUMBER  FUNCTION
SELECT ROUND(2.053,0) FROM DUAL;
--5]ROUND NUMBER  FUNCTION
SELECT ROUND(2765.053,-2) FROM DUAL;
--6]ROUND NUMBER FUNCTION
SELECT ROUND(78456,-2)FROM DUAL;
--7]TRUNC NUMBER FUNCTION 
SELECT TRUNC(78893,-3)FROM DUAL;
--8]TRUNC NUMBER FUNCTION 
SELECT TRUNC(78893.786,-3)FROM DUAL;
--9]TRUNC NUMBER FUNCTION 
SELECT TRUNC(78893.786,3)FROM DUAL;
--10]BETWEEN AND
SELECT * FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01-06-05' AND '01-06-06';
--11]IS NULL
SELECT * FROM EMPLOYEES
WHERE MANAGER_ID IS NULL AND SALARY >14500;
--12]lIKE OR
SELECT * FROM EMPLOYEES
WHERE LAST_NAME LIKE '%h%' OR LAST_NAME LIKE '%p%'; 
--13]IN AND
SELECT * FROM EMPLOYEES WHERE JOB_ID IN('IT_PROG','SR_PROG') AND SALARY<20000; 
--] MAX 
SELECT MAX(SUM(SALARY))AS MAX_SALARY FROM EMPLOYEES;---WITHOUT GROUP BY NOT WORK ITS FALSE 
--14]ROUND DATE FUNCTION
SELECT HIRE_DATE,
ROUND(HIRE_DATE,'MONTH')FROM EMPLOYEES;
--15]ROUND DATE FUNCTION
SELECT ROUND(SYSDATE,'MONTH')DATE_ FROM DUAL;
--17]ROUND DATE FUNCTION
SELECT ROUND(SYSDATE,'YEAR')FROM DUAL;
--18]TRUNC DATE FUNCTION
SELECT hire_date,
TRUNC(hire_date,'MONTH')FROM EMPLOYEES;
--19]TRUNC DATE FUNCTION
SELECT hire_date,
TRUNC(hire_date,'YEAR')FROM EMPLOYEES;
--20]TRUNC DATE FUNCTION
SELECT TRUNC(hire_date, 'MONTH')
FROM EMPLOYEES;

--21]MOD NUMBER FUNCTION
SELECT MOD(12346,67)
FROM DUAL;
--22]MOD NUMBER FUNCTION
SELECT MOD(12346,-67)
FROM DUAL;
--23]MOD NUMBER FUNCTION
SELECT MOD(156.56,6)
FROM DUAL;
--24]MOD NUMBER FUNCTION
SELECT MOD(156.56,-6)
FROM DUAL;
--25]ADD_MONTHS FUNCTION
SELECT ADD_MONTHS(SYSDATE,6)
FROM DUAL;
--26]ADD_MONTHS FUNCTION
SELECT HIRE_DATE,ADD_MONTHS(HIRE_DATE,6)AS NEW_DATE
FROM EMPLOYEES;
--27]NEST_DAY FUNCTION
SELECT NEXT_DAY(SYSDATE,'FRIDAY')AS NEW_DAY FROM DUAL;
--28]NEST_DAY FUNCTION
SELECT NEXT_DAY(HIRE_DATE,'FRIDAY')AS NEW_DAY FROM EMPLOYEES;
--29]LAST DAY FUNCTION
SELECT LAST_DAY(SYSDATE)FROM DUAL;
--30]TRUNC DATE
SELECT TRUNC(SYSDATE,'MONTH') FROM DUAL;
--31]TRUNC DATE
SELECT TRUNC(SYSDATE,'YEAR') FROM DUAL;
--32]ROUND DATE
SELECT ROUND(SYSDATE,'YEAR') FROM DUAL;
--33]ROUND DATE
SELECT ROUND(SYSDATE,'MONTH') FROM DUAL;
--34]GENERIC FUNCTION NVL
SELECT NVL(NULL,'HI')AS OP FROM DUAL;
--35]GENERIC FUNCTION NVL
SELECT SALARY ,COMMISSION_PCT,
NVL(COMMISSION_PCT,0)
AS NEW_SALARY 
FROM EMPLOYEES;
--36]GENERIC FUNCTION NVL
SELECT FIRST_NAME,MANAGER_ID,
NVL(MANAGER_ID,0)
AS NEW_ID 
FROM EMPLOYEES;
--37]GENERIC FUNCTION NVL
SELECT DEPARTMENT_ID,MANAGER_ID,
NVL(MANAGER_ID,0)
AS NEW_ID 
FROM DEPARTMENTS;
--38]GENERIC FUNCTION NVL
SELECT STATE_PROVINCE,
NVL(STATE_PROVINCE,0)
AS NEW_LOC 
FROM LOCATIONS;
--39]GENERIC FUNCTION NVL
SELECT LOCATION_ID,CITY,STATE_PROVINCE,
NVL(STATE_PROVINCE,0)
AS NEW_LOC 
FROM LOCATIONS;
--35]GENERIC FUNCTION NVL
SELECT SALARY ,COMMISSION_PCT,
NVL(COMMISSION_PCT,0)
AS NEW_SALARY 
FROM EMPLOYEES;
--40]GENERIC FUNCTION NVL
SELECT FIRST_NAME,MANAGER_ID,
NVL(MANAGER_ID,0)
AS NEW_ID 
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%p%';
--41]NVL2 FUNCTION
SELECT FIRST_NAME,MANAGER_ID,
NVL2(MANAGER_ID,MANAGER_ID,0)
AS NEW_ID 
FROM EMPLOYEES;
--42]NVL2 FUNCTION
SELECT NVL2(NULL,'HI','HELLO')
FROM DUAL;
--43]NVL2 FUNCTION
SELECT NVL2('WELCOME','HI','HELLO')
FROM DUAL;
--44]NULLIF FUNCTION
SELECT NULLIF('HI','HI')AS OP
FROM DUAL;
--44]NULLIF FUNCTION
SELECT LAST_NAME,JOB_ID ,NULLIF(LAST_NAME,JOB_ID)AS OP
FROM EMPLOYEES;
--45]NULLIF FUNCTION
SELECT DEPARTMENT_ID,DEPARTMENT_ID ,NULLIF(EMPLOYEE_ID,DEPARTMENT_ID)AS OP
FROM EMPLOYEES;
--46] COALESCE FUNCTION 
SELECT COALESCE(100,200,300,NULL)
FROM DUAL;
--47] COALESCE FUNCTION 
SELECT COALESCE(NULL,NULL,300) OP
FROM DUAL;
--48] COALESCE FUNCTION 
SELECT COALESCE(200,400,500)OP
FROM DUAL;
--49] COALESCE FUNCTION 
SELECT LAST_NAME,COMMISSION_PCT,MANAGER_ID,COALESCE(MANAGER_ID,COMMISSION_PCT,-1)OP
FROM EMPLOYEES;
--50] COALESCE FUNCTION 
SELECT CITY,STATE_PROVINCE,COALESCE(STATE_PROVINCE,'HI','HELLO')OP
FROM LOCATIONS;
--50] COALESCE FUNCTION 
SELECT MANAGER_ID,COALESCE(MANAGER_ID,0,1)OP
FROM DEPARTMENTS;
--51]ORDER BY
SELECT LAST_NAME ,FIRST_NAME,COMMISSION_PCT
FROM EMPLOYEES
ORDER BY COMMISSION_PCT DESC;
--53]ORDER BY
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS
ORDER BY DEPARTMENT_NAME DESC;
--54]ORDER BY
SELECT CITY,LOCATION_ID
FROM LOCATIONS
ORDER BY LOCATION_ID DESC;
--55] COALESCE FUNCTION 
SELECT LAST_NAME,MANAGER_ID,COMMISSION_PCT,COALESCE(COMMISSION_PCT,MANAGER_ID,-1)OP
FROM EMPLOYEES;
--56] COALESCE FUNCTION 
SELECT COALESCE(100,NULL,400)OP
FROM DUAL;
--57]ORDER BY
SELECT CITY,LOCATION_ID
FROM LOCATIONS
ORDER BY LOCATION_ID ASC;
--58]ORDER BY
SELECT LOWER(CITY),LOCATION_ID
FROM LOCATIONS
ORDER BY LOCATION_ID DESC;
--59]
SELECT UPPER(CITY),LOCATION_ID
FROM LOCATIONS
ORDER BY LOCATION_ID DESC;
--60]ROUND NUMBER
SELECT SALARY,ROUND(SALARY,2) NEW_SAL
FROM EMPLOYEES
ORDER BY MANAGER_ID DESC;

--****************
SELECT SALARY,ROUND(SALARY+SALARY*0.2,2) NEW_SAL
FROM EMPLOYEES
ORDER BY MANAGER_ID DESC;
--**********lIKE OR
SELECT UPPER(LAST_NAME)NEW_NAME 
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%h%' OR LAST_NAME LIKE '%p%'; 
--*******lIKE OR
SELECT UPPER(LAST_NAME)NEW_NAME 
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%_n%'; 
--*******lIKE 
SELECT UPPER(CITY_NAME)NEW_NAME 
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%_n%'; 
--******WAQD CALCULATE EXPERIENCE OF EMPLOYEE
SELECT HIRE_DATE,TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12)AS EXPERIENCE
FROM EMPLOYEES;
--*******************************************************
--1]sum function
SELECT SUM(SALARY)AS SAL
FROM EMPLOYEES;
--2]MAX FUNCTION
SELECT MAX(SALARY)MAX_SAL
FROM EMPLOYEES;
--3]AVG FUNCTION
SELECT AVG(SALARY) AVG_SAL
FROM EMPLOYEES;
--4]MIN FUNCTION
SELECT MIN(SALARY) MIN_SAL
FROM EMPLOYEES;
--5]COUNT FUNCTION
SELECT COUNT(SALARY) COUNT_SAL
FROM EMPLOYEES
WHERE JOB_ID='IT_PROG';
--6]COUNT FUNCTION
SELECT COUNT(DEPARTMENT_ID) COUNT_DEPT
FROM DEPARTMENTS;
--7]COUNT *
SELECT COUNT(*)
FROM DEPARTMENTS;
--8]COUNT(EXP)
SELECT COUNT(SALARY)AS SAL,MIN(COMMISSION_PCT) AS COMM
FROM EMPLOYEES;
--9]COUNT (DISTINCT(EXP))
SELECT COUNT (DISTINCT(COMMISSION_PCT))COUNT_COMM
FROM EMPLOYEES;
--10]TO_CHAR FUNCTION
SELECT TO_CHAR(SYSDATE,'YYYY/MM/DD')NEW_DATE
FROM DUAL;
--11]TO_DATE FUNCTION
SELECT TO_DATE('07/08/2008','DD/MM/YYYY')NEW_DATE
FROM DUAL;
--12]TO_CHAR FUNCTION
SELECT TO_CHAR(HIRE_DATE,'DD/MON/YYYY')AS NEW_DATE
FROM EMPLOYEES;
--13]TO_DATE
SELECT TO_DATE('09/03/2003','MM/DD/YYYY') NEW_DATE
FROM DUAL;
--14]WAQD CALCULATE AVERAGE OF COMMISSION_PCT ON EMPLOYEE
SELECT AVG(COMMISSION_PCT)AS COMM ,MIN(SALARY)AS SAL
FROM EMPLOYEES 
WHERE JOB_ID='IT_PROG';  
--15]WAQD CALCULATE AVG MIN MAX ON SALARY
SELECT AVG(SALARY)AS COMM ,MIN(SALARY)AS SAL_MIN,MAX(SALARY)AS SAL_MIN
FROM EMPLOYEES 
WHERE JOB_ID='IT_PROG';  
--16]DISTINCT
SELECT DISTINCT(COMMISSION_PCT)
FROM EMPLOYEES;
--17]DISTINCT COUNT
SELECT DISTINCT(COUNT(COMMISSION_PCT))AS COMM
FROM EMPLOYEES;
--18]TO_CHAR
SELECT TO_CHAR(HIRE_DATE,'DAY/MONTH/YEAR')
FROM EMPLOYEES;
--19]TO_DATE
SELECT TO_DATE('2003/02/22','YYYY/MM/DD')AS NEW_DATE
FROM DUAL;
--20]DISTINCT WITH LIKE
SELECT DISTINCT(DEPARTMENT_NAME)AS NEW_NAME
FROM DEPARTMENTS
WHERE DEPARTMENT_NAME LIKE '%O%';

--****** GROUP BY CLAUSE
--1]WAQD DISPLAY SUM OF SALARY ALONG WITH JOB_ID
SELECT JOB_ID,SUM(SALARY)NEW_SALARY
FROM EMPLOYEES
GROUP BY JOB_ID;

--2]WAQD DISPLAY COUNT OF EMPLOYEE ALONG WITH WITH JOB_ID ,DEPARTMENT_ID
SELECT JOB_ID,DEPARTMENT_ID,COUNT(EMPLOYEE_ID)NO_EMP
FROM EMPLOYEES
GROUP BY JOB_ID,DEPARTMENT_ID;

--3]WAQD DISPLAY COUNT(*) OF EMPLOYEE ALONG WITH JOB_ID ,DEPARTMENT_ID
SELECT JOB_ID,DEPARTMENT_ID,COUNT(*)NO_EMP
FROM EMPLOYEES
GROUP BY JOB_ID,DEPARTMENT_ID;


--4]WAQD DISPLAY OF DEPARTMENTS ALONG WITH DEPARTMENT_NAME ORDER BY MANAGER_ID
SELECT DEPARTMENT_NAME,COUNT(MANAGER_ID)AS DETAILS
FROM DEPARTMENTS
GROUP BY DEPARTMENT_NAME
ORDER BY DEPARTMENT_NAME DESC;

--5]WAQD DISPLAY OF LOCATIONS ALONG WITH CITY,COUNTRY_ID ALSO DESC ORDERBY CITY 
SELECT CITY,COUNTRY_ID,COUNT(*)AS CONUT_LOC
FROM LOCATIONS
WHERE CITY LIKE '%r%'
GROUP BY CITY,COUNTRY_ID
ORDER BY CITY DESC;

--6]WAQD Calculate maximum salary of employee along with manager_id
SELECT MANAGER_ID,MAX(SALARY)
FROM EMPLOYEES
GROUP BY MANAGER_ID;

--7]WAQD Calculate minimum commission of employee along with department_id
SELECT DEPARTMENT_ID,MIN(COMMISSION_PCT)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

--8]WAQD Calculate Average commission of employee along with job_id
SELECT JOB_ID,AVG(COMMISSION_PCT)COMM
FROM EMPLOYEES
GROUP BY JOB_ID;


--9]WAQD Calculate maximum employee work in which department along with job_id also patten o present in job_id
SELECT JOB_ID,MAX(DEPARTMENT_ID)
FROM EMPLOYEES
WHERE JOB_ID LIKE '_T____'
GROUP BY JOB_ID;

--10]WAQD FULL NAME OF EMPLOYEE WHOSE SALRY >10000 ALONG WITH MANAGER_ID 
SELECT (FIRST_NAME|| ' '||LAST_NAME)AS FULL_NAME ,MANAGER_ID ,COUNT(EMPLOYEE_ID)
FROM EMPLOYEES 
WHERE SALARY > 10000 
GROUP BY MANAGER_ID,(FIRST_NAME|| ' '||LAST_NAME);
--11]WAQD Calculate maximum commission of employee along with manager_id, department_id
SELECT MANAGER_ID,DEPARTMENT_ID,MAX(COMMISSION_PCT) 
AS MAX_COMM
FROM EMPLOYEES
GROUP BY MANAGER_ID,DEPARTMENT_ID;
--12]WAQD DISPLAY DEPARTMENT ALONG WITH DEPARMENT NAME
SELECT DEPARTMENT_NAME,COUNT(*)AS DEPT_NAME
FROM DEPARTMENTS
GROUP BY DEPARTMENT_NAME;
--13]WAQD locations along with city ,state_province
SELECT CITY,STATE_PROVINCE,COUNT(*) COUNT_LOC
FROM LOCATIONS
GROUP BY CITY,STATE_PROVINCE;
--14]WAQD calculate total salary of those employee whose employee_id 100,102,103 along with job_Id
SELECT JOB_ID,SUM(SALARY)
FROM EMPLOYEES 
WHERE EMPLOYEE_ID IN (100,102,103)
GROUP BY JOB_ID;


--15]WAQD WAQD calculate MAX salary of those employee whose COMMISSION_PCT NULL 
--along with FIRST_NAME
SELECT FIRST_NAME,MAX(SALARY)MAX_SAL
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL
GROUP BY FIRST_NAME;
--16]WAQD TOTAL DEPARTMENNT NAME ALONG WITH MANAGER _ID
SELECT MANAGER_ID,COUNT(DEPARTMENT_NAME)TOTAL
FROM DEPARTMENTS
GROUP BY MANAGER_ID;

--17]WAQD total salary of employee whose job_id in between 0.1&0.3 along with first_name 
SELECT FIRST_NAME,SUM(SALARY)SAL
FROM EMPLOYEES 
WHERE COMMISSION_PCT BETWEEN 0.1 AND 0.3
GROUP BY FIRST_NAME;

--18]WAQD display employee count common joining date along with hire date 
SELECT HIRE_DATE,COUNT(HIRE_DATE)CNT
FROM EMPLOYEES
GROUP BY HIRE_DATE
ORDER BY HIRE_DATE;

--19]WAQD display employee count common joining date along with hire date here sort the count 
SELECT HIRE_DATE,COUNT(HIRE_DATE)CNT
FROM EMPLOYEES
GROUP BY HIRE_DATE
ORDER BY COUNT(HIRE_DATE) DESC;

--20]WAQD display count of city whose state_province is not null along with country_id  
SELECT COUNTRY_ID,COUNT(CITY)COUNT_CITY
FROM LOCATIONS
WHERE STATE_PROVINCE IS NOT NULL
GROUP BY COUNTRY_ID;
--*****************************************************************
--1]waqd department wise sumb of salary dispaly only department where sum of salary 
--greater than 20000.
SELECT DEPARTMENT_ID,SUM(SALARY)SAL
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID 
HAVING SUM(SALARY)> 20000;

--2]WAQD employee max and min salary along with job id display those employee
--who contain start letter A  
SELECT JOB_ID,MAX(SALARY)MIN_SAL,MIN(SALARY)MAX_SAL
FROM EMPLOYEES
WHERE JOB_ID LIKE 'A%'
GROUP BY JOB_ID;


--3]WAQD calculate job id wise total salary of those employee whose employee_id 100,102,103 
--only department where sum of salary greater 20000  
SELECT JOB_ID,SUM(SALARY)total
FROM EMPLOYEES 
WHERE EMPLOYEE_ID IN (100,102,103)
GROUP BY JOB_ID 
HAVING SUM(SALARY)>20000;


--4]WAQD calculate job id wise max salary of those employee 
--whose first name contain letter a only department where max of salary greater 20000 
SELECT JOB_ID,MAX(SALARY)MX_SAL
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%a%'
GROUP BY JOB_ID 
HAVING MAX(SALARY)>2000;



--5]WAQD display full name of employee commission is not null ,manager_id wise 
--avg salary  
SELECT (FIRST_NAME||' '||LAST_NAME)AS FULL_NAME,MANAGER_ID,AVG(SALARY)AS SAL
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY (FIRST_NAME||' '||LAST_NAME),MANAGER_ID;



--6]WAQD hiredate wise employee count ,count of emp >1
SELECT HIRE_DATE,COUNT(EMPLOYEE_ID)EMP
FROM EMPLOYEES
GROUP BY HIRE_DATE
HAVING COUNT(EMPLOYEE_ID)>1;


--7]WAQD hiredate wise employee count ,SUM of SALARY >20000
SELECT HIRE_DATE,COUNT(EMPLOYEE_ID)EMP
FROM EMPLOYEES
GROUP BY HIRE_DATE
HAVING SUM(SALARY)>20000;

--8]WAQD hiredate wise employee count ,SUM of SALARY >20000
SELECT LOCATION_ID,COUNT(CITY) AS CITIES
FROM LOCATIONS
GROUP BY LOCATION_ID;

--9]WAQD DEPARTMENT WISE SUM OF SALARY THOSE EMPLOYEE IN(10,20,30,40,50)
--SUM OF SALARY >2000AND ORDER DESC
SELECT DEPARTMENT_ID, SUM(salary)AS Total_Salary
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(10,20,30,40,50)
GROUP BY DEPARTMENT_ID
HAVING SUM(SALARY)>2000
ORDER BY DEPARTMENT_ID DESC;

--10]DEPARTMENT WISE COUNT ,COUNT COUNT IS LESS THAN 5 HERE DEPARTMENT IS NOT NULL 
SELECT DEPARTMENT_ID,COUNT(*) AS "TOTAL_COUNT"
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)<5;

--11]DEPARTMENT WISE COUNT ,COUNT COUNT IS LESS THAN 5 
SELECT DEPARTMENT_ID,COUNT(*) AS TOTAL_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)>6;

--12]COMMISSION_PCT AND MANAGER ID WISE COUNT OF MANAGER ,WHOSE COMMISSION_PCT
--NOT NULL THE MANAGER COUNT IS GRTER THAN 1  
SELECT  COMMISSION_PCT,MANAGER_ID,COUNT(*)
FROM EMPLOYEES 
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY MANAGER_ID,COMMISSION_PCT
HAVING COUNT(*)>1;

--13]WAQD job id wise count of employee count is >20;
SELECT JOB_ID,COUNT(*) AS cnt
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING COUNT(*)>=20;

--14]waqd managerid wise count of employee also count is >50
SELECT MANAGER_ID,COUNT(*) AS cnt
FROM EMPLOYEES
GROUP BY MANAGER_ID
HAVING COUNT(*)<50;

--15]WAQD MANAGER ID WISE SUM OF COMMISSION PCT COUNT OF 
--COMMISSION PCT <5 ALSO MANAGER ID AND COMMISSION PCT IS NOT NULL
SELECT MANAGER_ID,SUM(COMMISSION_PCT) AS COMM
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL AND COMMISSION_PCT IS NOT NULL
GROUP BY MANAGER_ID
HAVING COUNT(COMMISSION_PCT)<50;

--16]WAQD FULL OF EMPLOYEE WISE JOINING DATE COUNT COUNT=1
SELECT (FIRST_NAME||' '||LAST_NAME) AS Name,HIRE_DATE,COUNT(*)
FROM EMPLOYEES 
GROUP BY HIRE_DATE,(first_name||' '||last_name)
HAVING COUNT(*)=1;

--17]WAQD department wise count of department  nd manager count is=1;
SELECT DEPARTMENT_NAME,COUNT(*) AS cnt
FROM DEPARTMENTS
GROUP BY DEPARTMENT_NAME
HAVING COUNT(MANAGER_ID)=1;

--18]WAQD PHONE NUMBER WISE COUNT OF EMPLOYEE ND COUNT OF EMPLOYEE=1 ALSO
--PHONE NUMBER CONTAIN 423
SELECT PHONE_NUMBER,COUNT(EMPLOYEE_ID)TOTAL
FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '%423%'
GROUP BY PHONE_NUMBER
HAVING COUNT(EMPLOYEE_ID)>0; 

--19]WAQD location id wise count of city city contain 5 letter city count=1
SELECT LOCATION_ID,COUNT(CITY)COUNT_CITY
FROM LOCATIONS
WHERE CITY LIKE '_____'
GROUP BY LOCATION_ID
HAVING COUNT(CITY)=1;

--20]WAQD COUNTRY ID WISE COUNT OF CITY ALSO COUNT OF CITY =1
SELECT COUNTRY_ID,COUNT(CITY)
FROM LOCATIONS
GROUP BY COUNTRY_ID
HAVING COUNT(CITY)=1;

--**********************************************************
--1]WAQD
SELECT MANAGER_ID,SUM(SALARY)AS SAL
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID;

--2]WAQD TO_CHAR
SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY')AS T_DATE
FROM DUAL;
--3]TO_DATE
SELECT TO_DATE('08/05/2006','DD/MM/YYYY')T_DATE
FROM DUAL;
--4]LENGTH,SUBSTR
SELECT LENGTH(SUBSTR('INDIA IS MY COUNTRY',1,6))
AS STR 
FROM DUAL;
--5]INSTR
SELECT INSTR('INDIA IS MY COUNTRY','i',1,5)
FROM DUAL;
--6]ROUND
SELECT ROUND(35467,-5)FROM DUAL;
--7]ROUND
SELECT ROUND(45637,5)FROM DUAL;
--8]TRUNC
SELECT TRUNC(56478.67,-2) FROM DUAL;
--9]TRUNC
SELECT TRUNC(65437.7656678,3)FROM DUAL;
--10]TRUNC
SELECT TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE))MONTHS 
FROM EMPLOYEES;
--11]ADD_MONTHS
SELECT ADD_MONTHS(SYSDATE,5)DATES FROM DUAL;
--12]ROUND
SELECT ROUND(TO_DATE('26/11/2023','DD/MM/YYYY'),'MONTH')
FROM DUAL;
--13]ROUND
SELECT ROUND(TO_DATE('26/11/2023','DD/MM/YYYY'),'YEAR')FROM DUAL;
--14]TRUNC
SELECT TRUNC(TO_DATE('26/11/2024','DD/MM/YYYY'),'MONTH')
FROM DUAL;
--15]TRUNC
SELECT TRUNC(TO_DATE('26/11/2024','DD/MM/YYYY'),'YEAR')FROM DUAL;
--16]NEXT_DAY
SELECT NEXT_DAY(SYSDATE,'SATURDAY')FROM DUAL;
--17]LAST_DAY
SELECT LAST_DAY('07-05-2023')FROM DUAL;
--18]NVL
SELECT EMPLOYEE_ID,SALARY,NVL(MANAGER_ID,1)
FROM EMPLOYEES;
--19]NVL2
SELECT MANAGER_ID,NVL2(COMMISSION_PCT,COMMISSION_PCT,0)
FROM EMPLOYEES;
--20]NULLIF
SELECT CITY,POSTAL_CODE,LOCATION_ID,NULLIF(POSTAL_CODE,CITY)
FROM LOCATIONS;

--************************************************************
--1]
SELECT UPPER(CITY)AS CITIES,COUNT(LOCATION_ID)AS LOC
FROM LOCATIONS
GROUP BY UPPER(CITY);


--2]
SELECT LOWER(COUNTRY_ID)AS CITIES,COUNT(LOCATION_ID)AS LOC
FROM LOCATIONS
GROUP BY LOWER(COUNTRY_ID);

--3]
SELECT INITCAP(JOB_ID)AS JOBS,COUNT(EMPLOYEE_ID)AS EMP
FROM EMPLOYEES
GROUP BY INITCAP(JOB_ID);

--4]
SELECT LOWER(DEPARTMENT_NAME)AS DEPT,COUNT(DISTINCT(MANAGER_ID))AS MNG
FROM DEPARTMENTS
GROUP BY LOWER(DEPARTMENT_NAME);

--5]
SELECT LOWER(DEPARTMENT_NAME)AS DEPT,COUNT(DISTINCT(MANAGER_ID))AS MNG
FROM DEPARTMENTS
WHERE LOCATION_ID IN(1700,2400,1800)
GROUP BY LOWER(DEPARTMENT_NAME);

--6]
SELECT LOWER(DEPARTMENT_NAME)AS DEPT,COUNT(MANAGER_ID)AS MNG
FROM DEPARTMENTS
WHERE LOCATION_ID >=1700
GROUP BY LOWER(DEPARTMENT_NAME);
--7]
SELECT INITCAP(JOB_ID)AS JOBS,MAX(SALARY)AS SAL
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%r%'
GROUP BY INITCAP(JOB_ID);
--8]
SELECT UPPER(JOB_ID)AS JOBS,MIN(SALARY)AS SAL
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%r%'
GROUP BY UPPER(JOB_ID);
--9]
SELECT (JOB_ID) AS JOBS,MIN(SALARY)AS SAL_MIN,MAX(SALARY)AS SAL_MAX
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%r%'
GROUP BY (JOB_ID);
--10]
SELECT (JOB_ID) AS JOBS,MIN(SALARY)AS SAL_MIN,MAX(SALARY)AS SAL_MAX
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%O%'
GROUP BY (JOB_ID);
--11]
SELECT ADD_MONTHS(TO_DATE('09/03/2003','MM/DD/YYYY'),1) NEW_DATE
FROM DUAL;
--12]
SELECT MONTHS_BETWEEN(ADD_MONTHS(TO_DATE('09/03/2003','MM/DD/YYYY'),1),
'03-10-03') NEW_DATE
FROM DUAL;
--12]
SELECT ROUND(MONTHS_BETWEEN(ADD_MONTHS(TO_DATE('09/03/2003','MM/DD/YYYY'),1),
'03-10-03'),0) NEW_DATE
FROM DUAL;
--13]
SELECT TRUNC(MONTHS_BETWEEN(ADD_MONTHS(TO_DATE('09/03/2003','MM/DD/YYYY'),1),
'03-10-03'),11) NEW_DATE
FROM DUAL;
--14]
SELECT ROUND(MONTHS_BETWEEN(SYSDATE,ADD_MONTHS('25-Dec-2021',-3))/12,0) AS VAL
FROM DUAL;
--15]
SELECT UPPER(JOB_ID),MAX(SALARY)MX_SAL
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%r%'
GROUP BY UPPER(JOB_ID) 
HAVING MAX(SALARY)>6000;
--16]  
SELECT (FIRST_NAME||' '||LAST_NAME)AS FULL_NAME,MANAGER_ID,sum(SALARY)AS SAL
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL
GROUP BY (FIRST_NAME||' '||LAST_NAME),MANAGER_ID;
--17]
SELECT TO_DATE(HIRE_DATE,'DD/MM/YYYY')AS DATE_HIRING,COUNT(EMPLOYEE_ID)EMP
FROM EMPLOYEES
GROUP BY TO_DATE(HIRE_DATE,'DD/MM/YYYY')
HAVING COUNT(EMPLOYEE_ID)>1;
--18]
SELECT TO_CHAR(HIRE_DATE,'DD/MM/YYYY')AS DATE_HIRING,COUNT(EMPLOYEE_ID)EMP
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE,'DD/MM/YYYY')
HAVING COUNT(EMPLOYEE_ID)>=1;
--19]
SELECT TO_CHAR(HIRE_DATE,'DD/MON/YY')AS DATE_HIRING,COUNT(EMPLOYEE_ID)EMP
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE,'DD/MON/YY')
HAVING COUNT(EMPLOYEE_ID)>1;
--20]
SELECT TO_CHAR(HIRE_DATE,'DD/MON/YY')AS DATE_HIRING,COUNT(JOB_ID)EMP
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE,'DD/MON/YY')
HAVING COUNT(JOB_ID)>2;
--21]
SELECT ADD_MONTHS(SYSDATE,INSTR(CONCAT(SUBSTR('INDIA',8,3),
'LANGUE'),'E')) AS DETAILS FROM DUAL;
--22]
SELECT MONTHS_BETWEEN(ADD_MONTHS(SYSDATE,INSTR(CONCAT(SUBSTR('GEOGRAPHY',8,3),
'LANGUE'),'E')),SYSDATE) AS DETAILS FROM DUAL;
--23]
SELECT ROUND(MONTHS_BETWEEN(ADD_MONTHS(SYSDATE,INSTR(CONCAT(SUBSTR('GEOGRAPHY',8,3),
'LANGUE'),'E')),SYSDATE),0) AS DETAILS FROM DUAL;
--24]
SELECT * 
FROM LOCATIONS
WHERE UPPER(CITY) LIKE '%O%' 
AND STATE_PROVINCE IS NULL;
--25]
SELECT COUNTRY_ID,COUNT(LOCATION_ID)AS COUNTRY 
FROM LOCATIONS
GROUP BY COUNTRY_ID;
--26]
SELECT TO_CHAR(HIRE_DATE,'DD/MM/YY')AS DATES,COUNT(EMPLOYEE_ID)EMP
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE,'DD/MM/YY')
HAVING SUM(SALARY)>20000;
--27]
SELECT ROUND((LOCATION_ID),-3)AS LOC,COUNT(CITY) AS CITIES
FROM LOCATIONS
GROUP BY ROUND((LOCATION_ID),-3);
--28]
SELECT TRUNC((LOCATION_ID),-3)AS LOC,COUNT(CITY) AS CITIES
FROM LOCATIONS
GROUP BY TRUNC((LOCATION_ID),-3);
--29]
SELECT TRUNC((LOCATION_ID),-3)AS LOC,COUNT(CITY) AS CITIES
FROM LOCATIONS
WHERE LOCATION_ID=2700
GROUP BY TRUNC((LOCATION_ID),-3);
--30]
SELECT SUBSTR((CITY),1,2)AS LOC,COUNT(CITY) AS CITIES
FROM LOCATIONS
GROUP BY SUBSTR((CITY),1,2);
--31]
SELECT DEPARTMENT_ID, SUM(salary)AS Total_Salary
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(10,20,30,40,50)
GROUP BY DEPARTMENT_ID
HAVING SUM(SALARY)>2000
ORDER BY DEPARTMENT_ID DESC;

--32] 
SELECT DEPARTMENT_ID,COUNT(*) AS "TOTAL_COUNT"
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)<5;
--33]
SELECT JOB_ID,COUNT(DISTINCT(COMMISSION_PCT)) AS COMM
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL
GROUP BY JOB_ID
HAVING COUNT(*)<5;

--34]
SELECT JOB_ID,COUNT(COMMISSION_PCT) AS COMM
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
GROUP BY JOB_ID
HAVING COUNT(*)<2;

--35] 
SELECT DEPARTMENT_ID,COUNT(*) AS TOTAL_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)>6;

--36]
SELECT  COMMISSION_PCT,MANAGER_ID,COUNT(SALARY)
FROM EMPLOYEES 
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY MANAGER_ID,COMMISSION_PCT
HAVING COUNT(*)>1;

--37]
SELECT JOB_ID,COUNT(COMMISSION_PCT) AS COMM
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING COUNT(*)>=20;

--38]
SELECT COUNTRY_ID,COUNT(CITY)AS CITIES
FROM LOCATIONS
WHERE  STATE_PROVINCE IS NULL
GROUP BY COUNTRY_ID;

--39]
SELECT TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY'),'DD/MM/YYYY')AS T_DATE
FROM DUAL;

--40]
SELECT TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,0)AS TIME_P
FROM EMPLOYEES;

--3]TO_DATE
SELECT TO_DATE('08/05/2006','DD/MM/YYYY')T_DATE
FROM DUAL;

--4]LENGTH,SUBSTR
SELECT LENGTH(SUBSTR('INDIA IS MY COUNTRY',1,6))
AS STR 
FROM DUAL;
--*********************************************************
--JOIN
SELECT e.EMPLOYEE_ID,e.FIRST_NAME,e.PHONE_NUMBER,d.DEPARTMENT_ID,d.DEPARTMENT_NAME
FROM e.EMPLOYEES INNER JOIN d.DEPARTMENTS
ON (e.DEPARTMENT_ID = d.DEPARTMENT_ID);







