--create one table with pk

CREATE TABLE PERSON
(PID NUMBER (5)CONSTRAINT PER_PK PRIMARY KEY,NAME VARCHAR2(20),
ADDRESS VARCHAR2(20),EMAIL VARCHAR(20),SALARY NUMBER(8)
);
SELECT * FROM PERSON;

CREATE SEQUENCE PER_ID_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 0
MAXVALUE 10
NOCACHE
NOCYCLE;

SELECT * FROM PERSON;
INSERT INTO PERSON VALUES(PER_ID_SEQ.NEXTVAL,'KIRAN','PUNE','KIRAN1@2.COM',20000);
INSERT INTO PERSON VALUES(PER_ID_SEQ.NEXTVAL,'KOMAL','MUMBAI','KOM2@2.COM',15000);
INSERT INTO PERSON VALUES(PER_ID_SEQ.NEXTVAL,'SANKET','PANAJI','PAN1@2.COM',30000);
INSERT INTO PERSON VALUES(PER_ID_SEQ.NEXTVAL,'AKASH','RANCHI','AK@2.COM',50000);
INSERT INTO PERSON VALUES(PER_ID_SEQ.NEXTVAL,'REENA','NAGPUR','RENA@2.COM',60000);
INSERT INTO PERSON VALUES(PER_ID_SEQ.NEXTVAL,'KARUNA','NAGPUR','KR@2.COM',60800);
INSERT INTO PERSON VALUES(PER_ID_SEQ.NEXTVAL,'RENU','NASHIK','RE@2.COM',30800);
--Error starting at line : 24 in command -
--INSERT INTO PERSON VALUES(PER_ID_SEQ.NEXTVAL,'RENU','NASHIK','RE@2.COM',30800)
--Error report -
--ORA-08004: sequence PER_ID_SEQ.NEXTVAL exceeds MAXVALUE and cannot be instantiated
TRUNCATE TABLE PERSON;
SELECT * FROM PERSON;


SELECT * FROM PERSON;

--********************************************
--create one table without pk

CREATE TABLE SALESMAN
(SID NUMBER (5),NAME VARCHAR2(20),ADDRESS VARCHAR2(20),EMAIL VARCHAR(20),SALARY NUMBER(8)
);
SELECT * FROM SALESMAN;

CREATE SEQUENCE SER_ID_SEQUENCE
INCREMENT BY 1
START WITH 1
MINVALUE 0
MAXVALUE 5
NOCACHE
CYCLE;

INSERT INTO SALESMAN VALUES(SER_ID_SEQUENCE.NEXTVAL,'KIRAN','PUNE','KIRAN1@2.COM',20000);
INSERT INTO SALESMAN VALUES(SER_ID_SEQUENCE.NEXTVAL,'KOMAL','MUMBAI','KOM2@2.COM',15000);
INSERT INTO SALESMAN VALUES(SER_ID_SEQUENCE.NEXTVAL,'SANKET','PANAJI','PAN1@2.COM',30000);
INSERT INTO SALESMAN VALUES(SER_ID_SEQUENCE.NEXTVAL,'AKASH','RANCHI','AK@2.COM',50000);
INSERT INTO SALESMAN VALUES(SER_ID_SEQUENCE.NEXTVAL,'REENA','NAGPUR','RENA@2.COM',60000);
select * from SALESMAN;
INSERT INTO SALESMAN VALUES(SER_ID_SEQUENCE.NEXTVAL,'KARUNA','NAGPUR','KR@2.COM',60800);
INSERT INTO SALESMAN VALUES(SER_ID_SEQUENCE.NEXTVAL,'RENU','NASHIK','RE@2.COM',30800);
INSERT INTO SALESMAN VALUES(SER_ID_SEQUENCE.NEXTVAL,'UMA','SATARA','U@2.COM',60800);
