
--with
WITH TEMP_01 
AS
(
SELECT DEPARTMENT_ID , AVG(SALARY) AS AVG_SAL
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
) ,
TEMP_02
AS
( SELECT DEPARTMENT_ID , SUM(SALARY) AS SUM_SAL
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID 
)

SELECT t1.DEPARTMENT_ID , t1.AVG_SAL ,t2.SUM_SAL
FROM TEMP_01 t1 JOIN TEMP_02 t2
ON(t1.DEPARTMENT_ID = t2.DEPARTMENT_ID
AND t1.AVG_SAL = t2.SUM_SAL);

--LEFT OUTER JOIN******************************************
WITH TEMP_01 
AS
(
SELECT  e.EMPLOYEE_ID 
FROM EMPLOYEES e

)
SELECT e.EMPLOYEE_ID,e.first_name AS ENAME ,m.first_name
AS MGR_NAME
FROM employees e LEFT OUTER JOIN employees m
ON(m.EMPLOYEE_ID = e.MANAGER_ID) ;

--RIGHT OUTER JOIN****************************************
WITH TEMP_01 
AS
(
SELECT  e.EMPLOYEE_ID 
FROM EMPLOYEES e
),
TEMP_02
AS
( SELECT m.EMPLOYEE_ID
FROM EMPLOYEES m

)
SELECT e.EMPLOYEE_ID,m.first_name AS ENAME,e.first_name AS MGR_NAME 
FROM employees e RIGHT outer JOIN employees m
ON( m.MANAGER_ID=e.EMPLOYEE_ID) ;

--join*************************************************8
WITH TEMP_01 
AS
(
SELECT  EMPLOYEE_ID,FIRST_NAME 
FROM EMPLOYEES 
)
SELECT M.EMPLOYEE_ID,M.first_name AS ENAME ,E.first_name
AS MGR_NAME
FROM employees e JOIN employees m
ON(E.EMPLOYEE_ID = M.MANAGER_ID) ;





--with*****************************************
WITH TEMPTABLE
AS
(
SELECT  ROUND(AVG(SALARY)) AS AVG_SAL
FROM EMPLOYEES
)
SELECT EMPLOYEE_ID ,FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES,TEMPTABLE
WHERE EMPLOYEES.SALARY > TEMPTABLE.AVG_SAL ;



--*****************************
WITH TEMPTABLE
AS
(
SELECT  ROUND(AVG(SALARY)) AS AVG_SAL
FROM EMPLOYEES
)
SELECT EMPLOYEE_ID ,FIRST_NAME,LAST_NAME,SALARY,
(SALARY-AVG_SAL)AS SALARY_DIFF
FROM EMPLOYEES,TEMPTABLE;
--****************************



--RETRIVE NAMES AND SALARY WHO HAVE SALARY GREATER THAN AVG SALARY RESPECTIVE DEPARTMENTS

WITH TEMP_01 
AS
(
SELECT DEPARTMENT_ID, ROUND(AVG(SALARY),0) AS AVG_SAL
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID,FIRST_NAME
) ,
TEMP_02
AS
( SELECT DEPARTMENT_ID,salary,FIRST_NAME
FROM EMPLOYEES

)
SELECT t2.first_name,t1.DEPARTMENT_ID , t1.AVG_SAL ,t2.SALARY
FROM TEMP_01 t1 JOIN TEMP_02 t2
ON(t1.DEPARTMENT_ID = t2.DEPARTMENT_ID
AND  t2.SALARY>t1.AVG_SAL);



